[package]
name = "rust-randomart"
version = "0.1.1"
authors = ["Shelvacu <shelvacu@gmail.com>"]
edition = "2018"

[dependencies]
rgb = "0.8"
palette = "0.4"
lodepng = "^2.4"

[build-dependencies]
num = "*"
rand = "*"
rand_chacha = "*"
sha2 = "*"
